# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/mozao/.oh-my-zsh"

# PowerLevel9k Customizations
#neofetch
# Theme
ZSH_THEME="powerlevel9k/powerlevel9k"
# PowerLevel9k Font
POWERLEVEL9K_MODE="nerdfont-complete"
# Left and Right Elements
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_os_icon dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status ssh root_indicator background_jobs battery disk_usage ram time)
# Segments
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\ue0c6'
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\ue0c6'
POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS='  '
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\ue0c7'
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\ue0c7'
POWERLEVEL9K_WHITESPACE_BETWEEN_RIGHT_SEGMENTS='  '
# Truncate
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
# Prefix
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%F{007}╭─%F{007}'
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{007}╰%f '
# OS Icon
POWERLEVEL9K_CUSTOM_OS_ICON="echo $'\uE781'"
POWERLEVEL9K_CUSTOM_OS_ICON_BACKGROUND="007"
POWERLEVEL9K_CUSTOM_OS_ICON_FOREGROUND="black"
# Dir
POWERLEVEL9K_DIR_HOME_BACKGROUND="black"
POWERLEVEL9K_DIR_HOME_FOREGROUND="007"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="black"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="007"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="black"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="007"
# Status
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true
POWERLEVEL9K_STATUS_OK_BACKGROUND="black"
POWERLEVEL9K_STATUS_OK_FOREGROUND="007"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="black"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
# Wifi
#POWERLEVEL9K_CUSTOM_WIFI_SIGNAL="echo signal: \$(nmcli device wifi | grep yes | awk "{print \$8}")"
#POWERLEVEL9K_CUSTOM_WIFI_SIGNAL_BACKGROUND="blue"
#POWERLEVEL9K_CUSTOM_WIFI_SIGNAL_FOREGROUND="yellow"
# Battery
POWERLEVEL9K_BATTERY_LOW_BACKGROUND="black"
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND="black"
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND="black"
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND="black"
POWERLEVEL9K_BATTERY_LOW_FOREGROUND="007"
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND="007"
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND="007"
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND="007"
POWERLEVEL9K_BATTERY_LOW_VISUAL_IDENTIFIER_COLOR="black"
POWERLEVEL9K_BATTERY_CHARGING_VISUAL_IDENTIFIER_COLOR="yellow"
POWERLEVEL9K_BATTERY_CHARGED_VISUAL_IDENTIFIER_COLOR="007"
POWERLEVEL9K_BATTERY_DISCONNECTED_VISUAL_IDENTIFIER_COLOR="green"
# Disk_Usage
#POWERLEVEL9K_DISK_USAGE_ONLY_WARNING=true
POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL=50
POWERLEVEL9K_DISK_USAGE_CRITICAL_LEVEL=75
POWERLEVEL9K_DISK_USAGE_NORMAL_BACKGROUND="black"
POWERLEVEL9K_DISK_USAGE_NORMAL_FOREGROUND="007"
POWERLEVEL9K_DISK_USAGE_WARNING_BACKGROUND="black"
POWERLEVEL9K_DISK_USAGE_WARNING_FOREGROUND="yellow"
POWERLEVEL9K_DISK_USAGE_CRITICAL_BACKGROUND="black"
POWERLEVEL9K_DISK_USAGE_CRITICAL_FOREGROUND="red"
# Ram
POWERLEVEL9K_RAM_BACKGROUND="black"
POWERLEVEL9K_RAM_FOREGROUND="249"
POWERLEVEL9K_RAM_ELEMENTS=(ram_free)
# Date and Time
POWERLEVEL9K_TIME_FORMAT="%T"
POWERLEVEL9K_TIME_BACKGROUND="black"
POWERLEVEL9K_TIME_FOREGROUND="007"

# Plugins
plugins=(git)
source $ZSH/oh-my-zsh.sh

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing DHARMA Initiative Plugin Manager (zdharma/zinit)…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f" || \
        print -P "%F{160}▓▒░ The clone has failed.%f"
fi
source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit installer's chunk

# Plugins added by Zinit
zplugin light zdharma/fast-syntax-highlighting
zplugin light zsh-users/zsh-autosuggestions
zplugin light zsh-users/zsh-completions